name: Build and deploy services

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  FE_DIRECTORY: ./code/frontend
  FIRSTNAMES_DIRECTORY: ./code/firstnames
  SECONDNAMES_DIRECTORY: ./code/secondnames
  MERGE_DIRECTORY: ./code/merge
  
  FE_PACKAGE_PATH: ./code/frontend/publish
  NUMBERS_PACKAGE_PATH: ./code/firstnames/publish
  LETTERS_PACKAGE_PATH: ./code/secondnames/publish
  MERGE_PACKAGE_PATH: ./code/merge/publish

jobs:

  build-firstnames-service:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.FIRSTNAMES_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.FIRSTNAMES_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      - name: publish firstnames service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            cd "${{ env.FIRSTNAMES_DIRECTORY }}"
            az webapp up -n ckb-superherogen-firstnames --os-type Linux --resource-group ckb-superherogen-rg
  build-secondnames-service:
      runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        - name: Restore
          run: dotnet restore "${{ env.SECONDNAMES_DIRECTORY }}"
        - name: Build
          run: dotnet build "${{ env.SECONDNAMES_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
        - name: Publish
          run: dotnet publish "${{ env.SECONDNAMES_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.SECONDNAMES_PACKAGE_PATH }}"
    
        - name: publish numbers service to Azure
          run: az
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
            azcliversion: 2.25.0
            inlineScript: |
              cd "${{ env.SECONDNAMES_PACKAGE_PATH }}"
              az webapp up -n ckb-superherogen-secondnames --os-type Linux --resource-group ckb-superherogen-rg --runtime "DOTNET|5.0"
  build-merge-service:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.MERGE_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.MERGE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      - name: publish numbers service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            cd "${{ env.MERGE_DIRECTORY }}"
            az webapp up -n ckb-superherogen-merge --os-type Linux --resource-group ckb-superherogen-rg
            az webapp config appsettings set -g ckb-superherogen-rg -n ckb-superherogen-merge --settings "@../../.github/workflows/mergeSettings.json"
  build-frontend-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.FE_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.FE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      - name: publish numbers service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            cd "${{ env.FE_DIRECTORY }}"
            az webapp up -n ckb-superherogen-frontend --os-type Linux --resource-group ckb-superherogen-rg
            az webapp config appsettings set -g ckb-superherogen-merge -n ckb-superherogen-rg --settings "@../../.github/workflows/frontendSettings.json"
